name: "taskmaster-express"
services:
  api:
    build:
      target: dev
    ports:
      - 8001:8001
    env_file: .env
    environment:
      - PSQL_CONNECTION_STRING=postgresql+asyncpg://taskmaster:password@db/taskmaster
      - REDIS_URL=redis://redis:6379
      - FASTAPI_DOCUMENTATION=true
      - CORS_ORIGINS=http://localhost:4200,https://taskmaster.local
    command: "sh scripts/launch-api.local.sh"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
  test:
    image: taskmaster-express-api
    env_file: .env
    command: "sh scripts/test.sh"
    profiles: [ "test" ]
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=taskmaster
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
