name: "taskmaster-express"
services:
  api:
    build:
      context: ./api
      dockerfile: ../docker/api.dockerfile
      target: app
    ports:
      - 8001:8001
    env_file: .env
    environment:
      - PSQL_CONNECTION_STRING=postgresql+asyncpg://taskmaster:password@db/taskmaster
    command: "sh scripts/launch-api.local.sh"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
  web:
    build:
      context: ./web/taskmaster
      dockerfile: ../../docker/web.dockerfile
      target: app
    ports:
      - 4200:4200
    env_file: .env
    command: "ng serve --host 0.0.0.0 --configuration development"
    volumes:
      - ./web/taskmaster/src:/usr/src/app/src
    depends_on:
      - api
  lint:
    image: taskmaster-express-api
    env_file: .env
    command: "sh scripts/lint.sh"
    profiles: [ "test" ]
    volumes:
      - ./api:/usr/src/app
  test:
    image: taskmaster-express-api
    env_file: .env
    command: "sh scripts/test.sh"
    profiles: [ "test" ]
    volumes:
      - ./api:/usr/src/app
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=taskmaster
    ports:
      - "5432:5432"
  https-portal:
    image: steveltn/https-portal
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: 'taskmaster.local -> http://web:4200'
      STAGE: 'local'
      WEBSOCKET: true
    depends_on:
      - web
