"""add relationship between tasks and user

Revision ID: 7784b898ebe9
Revises: ce56245aa38a
Create Date: 2024-06-10 15:35:39.908668

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7784b898ebe9"
down_revision: Union[str, None] = "ce56245aa38a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("u_users_email", "users", ["email"])
    op.add_column("tasks", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_foreign_key("fk_tasks_users", "tasks", "users", ["user_id"], ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("u_users_email", "users", type_="unique")
    op.drop_constraint("fk_tasks_users", "tasks", type_="foreignkey")
    op.drop_column("tasks", "user_id")
    # ### end Alembic commands ###
