"""Add main priority task

Revision ID: 390c24500e6b
Revises: 6d02dd7f2b6c
Create Date: 2024-10-25 15:13:57.739773

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "390c24500e6b"
down_revision: Union[str, None] = "6d02dd7f2b6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "is_main_priority", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "is_main_priority")
    # ### end Alembic commands ###
